### ISSUE TITLE
When used with Weight Tweaks the mod causes stuttering

### ISSUE THREAD

**Issue by Arkhorse** [Thekillergreece/FoodPackByTKG#2]
As the title states, these two mods in combination results in stuttering if any items this mod alters is in the players inventory. This was tested by simply putting anything with weight into a container and then moving around. The stuttering effectively vanished. Taking those items immediately resulted in the stuttering returning. Please let me know anything else you need to know to help fix the issue
## Logs
[Player.log](https://github.com/Thekillergreece/FoodPackByTKG/files/11245061/Player.log)
[Latest.log](https://github.com/Thekillergreece/FoodPackByTKG/files/11245063/Latest.log)

**Comment by Thekillergreece** [comment]
Probably some issue with other mod such as weight tweaks.
