### ISSUE TITLE
Thank you and two questions

### ISSUE THREAD

**Issue by Lev234** [Thekillergreece/FoodPackByTKG#9]
Whoever designed this mod, especially the designer, should have a separate place in paradise. I am also a designer, and I would like to learn from you, even if it is paid. When I watched the video with the review of the new food, I was pleasantly surprised to see that some of the textures of the food were translated into Russian. But unfortunately, my food mods refuse to launch. What can the modification conflict with?
![photo_1_2024-10-05_20-07-50](https://github.com/user-attachments/assets/4f3169ea-434c-4df0-9376-f886f8109c75)
![photo_2_2024-10-05_20-07-50](https://github.com/user-attachments/assets/96bcda1a-7b0d-424d-9ca2-ae4640d6bf64)

**Comment by Thekillergreece** [comment]
Hey, join the modding discord and we'll try to help you in #troubleshooting channel. 
I'll contact the artist on your behalf as well. https://discord.gg/jWxVa9JZ
